/*
 * This source file was generated by the Gradle 'init' task
 */
package wordleclone;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GameDriver classUnderTest = new GameDriver();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
